<script>
	// terms-consent — QUESTION TWO, and the second half of chapter one's straight
	// opening. The format is still an ordinary five-point agree/disagree; only the
	// thing being agreed to has grown to four thousand words.
	//
	// THE CLAUSE IS THE QUESTION. Section 5.4 asks, in the flattest possible
	// voice and with no formatting of any kind to distinguish it, whether the
	// taker will hand over a dollar. It is a survey item smuggled into a contract,
	// sitting between an indemnity clause and a severability clause, and the
	// entire design of this component exists to guarantee it passes under their
	// eyes at least once.
	//
	// Hence the gate: the Likert row stays disabled until the document has
	// actually been scrolled to its end. That is the real dark pattern being
	// parodied — not the legalese, which everyone expects, but the fact that
	// forcing someone to scroll past something is treated as having informed them
	// of it. `dwell` records how long that scroll took, because a taker who
	// reaches the bottom of four thousand words in six seconds has told us
	// something they did not mean to.
	//
	// Nothing here winks. No clause is bolded, no aside acknowledges the joke, and
	// the quiz never returns to say "gotcha" — per P6, if the taker misses 5.4
	// entirely, they simply miss it.
	import LikertPick from './LikertPick.svelte';

	let { onAnswer } = $props();

	const prompt = 'Do you consent to the following terms and conditions?';

	// Agreeing to an unread contract is fast, broad-strokes and exposed; refusing
	// is slow, granular and safe. Nobody is scored on whether they SAW 5.4 —
	// only on what they were willing to sign.
	/** @type {Record<string, number>[]} */
	const SCORES = [
		{ risk: -2, scope: -2, honesty: 1 },
		{ risk: -1, scope: -1 },
		{},
		{ risk: 1, scope: 1, tempo: 1 },
		{ risk: 2, scope: 2, tempo: 2 }
	];

	// Buried at 5.4. Keep it mid-document — a clause in the first section gets
	// read, a clause in the last gets read on the way to the buttons.
	const sections = [
		{
			n: '1.',
			title: 'Acceptance of Terms',
			body: [
				'By accessing, viewing, scrolling, or otherwise interacting with this assessment (the "Assessment"), you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions (the "Terms"), together with any documents incorporated herein by reference. If you do not agree to these Terms, you should not proceed beyond this point, although no mechanism has been provided by which you might do so.',
				'The Provider reserves the right to amend, modify, supplement, or replace these Terms at any time and without notice, and your continued use of the Assessment following any such amendment shall constitute acceptance thereof. You are advised to review these Terms periodically. The Provider is under no obligation to inform you when a review would be advisable.'
			]
		},
		{
			n: '2.',
			title: 'Nature of the Assessment',
			body: [
				'The Assessment is provided for entertainment purposes only and does not constitute psychological, psychiatric, medical, legal, financial, vocational, or spiritual advice. No clinical instrument has been used in its preparation, no instrument has been validated against it, and no practitioner has reviewed it. Any resemblance between the Assessment and a diagnostic tool is coincidental and should not be relied upon.',
				'You acknowledge that the results produced by the Assessment are generated by a process which the Provider is not obliged to disclose, explain, justify, or defend, and that such results may be inaccurate, unflattering, internally inconsistent, or all three.'
			]
		},
		{
			n: '3.',
			title: 'Eligibility and Representations',
			body: [
				'You represent and warrant that you are of the age of majority in your jurisdiction of residence, that you possess the legal capacity to enter into binding agreements, and that you are answering the Assessment on your own behalf and not on behalf of any other natural person, legal person, corporate entity, or estate.',
				'You further represent that the answers you provide will be your own, given in good faith, and not the product of collusion, coordination, or consultation with any third party. The Provider has no means of verifying this representation and will make no attempt to.'
			]
		},
		{
			n: '4.',
			title: 'Data and Retention',
			body: [
				'Responses submitted in the course of the Assessment are retained in the volatile memory of your own device for the duration of your session and are discarded when that session ends. No responses are transmitted to the Provider, to any affiliate of the Provider, or to any third party, and no persistent identifier is assigned to you.',
				'Notwithstanding the foregoing, you acknowledge that your device, your browser, your network operator, and any intermediary through which your connection passes may retain records of your activity independently of the Provider, and that the Provider exercises no control over and accepts no responsibility for such records.'
			]
		},
		{
			n: '5.',
			title: 'Consideration and Contributions',
			body: [
				'5.1 The Assessment is made available to you at no charge. No fee is payable for access, and no payment information is collected at the point of use.',
				'5.2 The Provider derives no revenue from the Assessment and makes no representation as to its continued availability, which may be discontinued at any time and for any reason without notice to you.',
				'5.3 Voluntary contributions, where offered, are non-refundable and confer no additional rights, privileges, results, or standing of any kind, whether in respect of the Assessment or otherwise.',
				// The clause. Deliberately unstyled, unbolded, and no longer than
				// its neighbours — it must read as one more item in a list.
				'5.4 If prompted, will you agree to provide at least $1 of donation to the creator of this quiz?',
				'5.5 Any contribution made under clause 5.4 shall be treated as a gratuitous transfer and not as consideration for services rendered, and shall not create any contract for services between you and the Provider.'
			]
		},
		{
			n: '6.',
			title: 'Intellectual Property',
			body: [
				'All content comprising the Assessment, including without limitation its text, questions, response options, layout, typography, imagery, source code, and the particular sequence in which the foregoing are presented, is the property of the Provider or of its licensors and is protected by applicable intellectual property law.',
				'You are granted a limited, personal, non-exclusive, non-transferable, revocable licence to access the Assessment for your own non-commercial use. Nothing in these Terms shall be construed as conferring any licence to reproduce, adapt, distribute, publicly perform, or create derivative works from the Assessment or any part of it.'
			]
		},
		{
			n: '7.',
			title: 'Disclaimer of Warranties',
			body: [
				'THE ASSESSMENT IS PROVIDED "AS IS" AND "AS AVAILABLE", WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR ARISING FROM COURSE OF DEALING OR USAGE OF TRADE. THE PROVIDER SPECIFICALLY DISCLAIMS ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.',
				'Without limiting the generality of the foregoing, the Provider does not warrant that the Assessment will be uninterrupted, timely, secure, or error-free, that its results will be accurate or reliable, or that it will describe you in terms you find agreeable.'
			]
		},
		{
			n: '8.',
			title: 'Limitation of Liability and Indemnity',
			body: [
				'To the maximum extent permitted by applicable law, the Provider shall not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, including without limitation damages for loss of profits, goodwill, data, dignity, or self-conception, arising out of or in connection with your use of the Assessment, whether based in contract, tort, strict liability, or otherwise, and whether or not the Provider has been advised of the possibility of such damages.',
				'You agree to indemnify, defend, and hold harmless the Provider and its officers, directors, employees, agents, and licensors from and against any claim, demand, loss, liability, or expense (including reasonable legal fees) arising out of your use of the Assessment or your breach of these Terms.'
			]
		},
		{
			n: '9.',
			title: 'Severability, Waiver, and Entire Agreement',
			body: [
				'If any provision of these Terms is held by a court of competent jurisdiction to be invalid, illegal, or unenforceable, that provision shall be severed and the remaining provisions shall continue in full force and effect. No failure or delay by the Provider in exercising any right under these Terms shall operate as a waiver of that right.',
				'These Terms constitute the entire agreement between you and the Provider with respect to the Assessment and supersede all prior or contemporaneous understandings, whether written or oral. You confirm that you have not relied upon any representation not expressly set out herein.'
			]
		}
	];

	let reachedEnd = $state(false);

	// Wall clock, not the animation clock — the patience governor must never
	// flatter or punish a reading speed. Set on mount, read once at the end.
	let openedAt = Date.now();
	let dwell = 0;

	/** @param {Event & { currentTarget: HTMLElement }} e */
	function onScroll(e) {
		if (reachedEnd) return;
		const el = e.currentTarget;
		// 24px of slack: sub-pixel line heights and zoom levels routinely leave
		// scrollTop + clientHeight a hair short of scrollHeight at the true
		// bottom, which would strand the taker on a permanently disabled row.
		if (el.scrollTop + el.clientHeight >= el.scrollHeight - 24) {
			reachedEnd = true;
			dwell = Date.now() - openedAt;
		}
	}

	/** @param {number} i */
	function toScore(i) {
		const delta = { ...SCORES[i] };
		// A thousand words in under fifteen seconds is not reading, and the axis
		// it moves is scope: you took the gist and skipped the detail. It is
		// additive rather than a separate verdict, so a fast skim that still
		// refuses to sign reads as decisive rather than careless.
		if (dwell > 0 && dwell < 15000) {
			delta.scope = (delta.scope ?? 0) + 1;
			delta.tempo = (delta.tempo ?? 0) + 1;
		}
		return delta;
	}

</script>

<LikertPick
	{prompt}
	{toScore}
	{onAnswer}
	locked={!reachedEnd}
	lockedHint="Please read to the end of the terms to continue."
>
	{#snippet children()}
		<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
		<div
			class="doc"
			tabindex="0"
			role="region"
			aria-label="Terms and conditions"
			onscroll={onScroll}
		>
			<p class="doc-head">Terms and Conditions of Use</p>
			<p class="doc-sub">Last revised: this morning. Version 4.2.1.</p>

			{#each sections as sec}
				<section>
					<h3>{sec.n}&nbsp;&nbsp;{sec.title}</h3>
					{#each sec.body as para}
						<p>{para}</p>
					{/each}
				</section>
			{/each}

			<p class="doc-end">— End of Terms —</p>
		</div>
	{/snippet}
</LikertPick>

<style>
	/* Only the document itself lives here — the prompt, rule, five-point row and
	   locked hint are all LikertPick's, shared verbatim with memory-claim. */

	/* Fixed height, not max-height: the scrollbar must be present from the first
	   frame so the length of the document is legible before any of it is read. */
	.doc {
		height: 20rem;
		overflow-y: auto;
		padding: 1.25rem 1.4rem;
		margin-bottom: 1.5rem;
		background: var(--surface);
		border: 1px solid var(--rule);
		border-radius: var(--radius);
		font-size: 0.78rem;
		line-height: 1.65;
		color: var(--muted);
		text-align: justify;
	}
	.doc:focus-visible {
		outline: 2px solid var(--ink);
		outline-offset: 2px;
	}
	.doc-head {
		margin: 0 0 0.15rem;
		font-size: 0.9rem;
		font-weight: 700;
		color: var(--ink);
		text-align: center;
	}
	.doc-sub {
		margin: 0 0 1.5rem;
		font-size: 0.7rem;
		text-align: center;
		font-style: italic;
	}
	.doc section {
		margin-bottom: 1.35rem;
	}
	.doc h3 {
		margin: 0 0 0.5rem;
		font-size: 0.78rem;
		font-weight: 700;
		color: var(--ink);
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}
	.doc p {
		margin: 0 0 0.6rem;
	}
	.doc-end {
		margin: 1.5rem 0 0 !important;
		text-align: center;
		font-style: italic;
		letter-spacing: 0.08em;
	}

	@media (max-width: 560px) {
		.doc {
			height: 16rem;
			text-align: left;
		}
	}
</style>
