// GENERATED by scripts/fetch-plants.mjs — do not edit by hand.
//
// 128 plant photographs from Wikimedia Commons, each stored
// UNMODIFIED (display sizing is CSS only, so no derivative is distributed and
// the ShareAlike term on the CC BY-SA images is never triggered).
//
// Every entry carries the attribution its license requires: author, license
// name, license URL where one exists, and a link to the Commons file page.
// Full list also mirrored in CREDITS.md at the repo root.
//
// ORDER IS THE MAPPING. plantFor() in personalities.js indexes this array by
// the 7-bit type code, so reordering this list re-rolls every assignment.

/**
 * @typedef {{ common: string, scientific: string, file: string,
 *   artist: string, license: string, licenseUrl: string, sourceUrl: string }} Plant
 */

/** @type {Plant[]} */
export const PLANTS = [
	{
		"common": "Titan arum",
		"scientific": "Amorphophallus titanum",
		"file": "/images/plants/amorphophallus-titanum.jpg",
		"artist": "Sailing moose",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Amorphophallus_titanum_(corpse_flower)_-_2.jpg"
	},
	{
		"common": "Welwitschia",
		"scientific": "Welwitschia mirabilis",
		"file": "/images/plants/welwitschia-mirabilis.jpg",
		"artist": "Thomas Schoch",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Welwitschia_mirabilis(2).jpg"
	},
	{
		"common": "Venus flytrap",
		"scientific": "Dionaea muscipula",
		"file": "/images/plants/dionaea-muscipula.jpg",
		"artist": "Noah Elhardt",
		"license": "CC BY-SA 2.5",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Venus_Flytrap_showing_trigger_hairs.jpg"
	},
	{
		"common": "Corpse lily",
		"scientific": "Rafflesia arnoldii",
		"file": "/images/plants/rafflesia-arnoldii.jpg",
		"artist": "LukeTriton",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Rafflesia_arnoldii,_Sumatra.jpg"
	},
	{
		"common": "Socotra dragon tree",
		"scientific": "Dracaena cinnabari",
		"file": "/images/plants/dracaena-cinnabari.jpg",
		"artist": "Alex38",
		"license": "CC BY 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Dragonblood_tree_in_Socotra_2.jpg"
	},
	{
		"common": "Baobab",
		"scientific": "Adansonia digitata",
		"file": "/images/plants/adansonia-digitata.jpg",
		"artist": "Ferdinand Reus from Arnhem, Holland",
		"license": "CC BY-SA 2.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Baobab_and_elephant,_Tanzania.jpg"
	},
	{
		"common": "Giant water lily",
		"scientific": "Victoria amazonica",
		"file": "/images/plants/victoria-amazonica.jpg",
		"artist": "Bilby",
		"license": "CC BY 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Victoria_amazonica_edit_1.jpg"
	},
	{
		"common": "Rajah pitcher plant",
		"scientific": "Nepenthes rajah",
		"file": "/images/plants/nepenthes-rajah.png",
		"artist": "Unknown author",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Nepenthes_rajah.png"
	},
	{
		"common": "Resurrection plant",
		"scientific": "Selaginella lepidophylla",
		"file": "/images/plants/selaginella-lepidophylla.jpg",
		"artist": "Unknown author",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Selaginella_lepidophylla_gruen.jpeg"
	},
	{
		"common": "Jackal food",
		"scientific": "Hydnora africana",
		"file": "/images/plants/hydnora-africana.jpg",
		"artist": "Lytton John Musselman",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:HydnoraAfricanaKarasburgDistrictNamibia2002Musselman.jpg"
	},
	{
		"common": "Hooker's lips",
		"scientific": "Psychotria elata",
		"file": "/images/plants/psychotria-elata.jpg",
		"artist": "Franz Xaver",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Psychotria_elata_1.jpg"
	},
	{
		"common": "Bee orchid",
		"scientific": "Ophrys apifera",
		"file": "/images/plants/ophrys-apifera.jpg",
		"artist": "Didier Descouens",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:(MHNT)_Ophrys_apifera_-_Villeneuve-l%C3%A8s-Bouloc_-_Flower.jpg"
	},
	{
		"common": "Sensitive plant",
		"scientific": "Mimosa pudica",
		"file": "/images/plants/mimosa-pudica.jpg",
		"artist": "Suyash.dwivedi",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Mimosa_pudica_in_September_month.jpg"
	},
	{
		"common": "Ginkgo",
		"scientific": "Ginkgo biloba",
		"file": "/images/plants/ginkgo-biloba.jpg",
		"artist": "EecherplazGinkgo06.jpg: Cayambe derivative work: Ginkgotree (talk)",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:GINKGOBAUM-2.jpg"
	},
	{
		"common": "Giant sequoia",
		"scientific": "Sequoiadendron giganteum",
		"file": "/images/plants/sequoiadendron-giganteum.jpg",
		"artist": "Mike Murphy",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Grizzly_Giant_Mariposa_Grove.jpg"
	},
	{
		"common": "Cape sundew",
		"scientific": "Drosera capensis",
		"file": "/images/plants/drosera-capensis.jpg",
		"artist": "NoahElhardt",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Drosera_capensis_bend.JPG"
	},
	{
		"common": "Queen of the Andes",
		"scientific": "Puya raimondii",
		"file": "/images/plants/puya-raimondii.jpg",
		"artist": "Pepe Roque",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Puya_raimondii_h%C3%A1bito.jpg"
	},
	{
		"common": "Wood's cycad",
		"scientific": "Encephalartos woodii",
		"file": "/images/plants/encephalartos-woodii.jpg",
		"artist": "Purves, M.",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Encephalartos_woodii_original_stem_Durban_Botanic_Gardens_04_09_2010.JPG"
	},
	{
		"common": "Brazilian Dutchman's pipe",
		"scientific": "Aristolochia gigantea",
		"file": "/images/plants/aristolochia-gigantea.jpg",
		"artist": "C T Johansson",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Aristolochia_gigantea-IMG_5523.jpg"
	},
	{
		"common": "Carrion flower",
		"scientific": "Stapelia gigantea",
		"file": "/images/plants/stapelia-gigantea.jpg",
		"artist": "Camilla Floros",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Stapelia_gigantea00.jpg"
	},
	{
		"common": "Baseball plant",
		"scientific": "Euphorbia obesa",
		"file": "/images/plants/euphorbia-obesa.jpg",
		"artist": "Andrew Hankey",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Euphorbia_obesa_obesa_15102244.jpg"
	},
	{
		"common": "Halfmens",
		"scientific": "Pachypodium namaquanum",
		"file": "/images/plants/pachypodium-namaquanum.jpg",
		"artist": "possibly Robert Jacob Gordon",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Pachypodium_namaquanum00.jpg"
	},
	{
		"common": "Wollemi pine",
		"scientific": "Wollemia nobilis",
		"file": "/images/plants/wollemia-nobilis.jpg",
		"artist": "AndyScott",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Wakehurst_Place_woodland_Wollemi_pine.jpg"
	},
	{
		"common": "Ghost pipe",
		"scientific": "Monotropa uniflora",
		"file": "/images/plants/monotropa-uniflora.jpg",
		"artist": "Sage Ross",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Monotropa_uniflora_in_Penwood_State_Park_3,_2009-07-03.jpg"
	},
	{
		"common": "Sacred lotus",
		"scientific": "Nelumbo nucifera",
		"file": "/images/plants/nelumbo-nucifera.jpg",
		"artist": "T.Voekler",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Sacred_lotus_Nelumbo_nucifera.jpg"
	},
	{
		"common": "Spanish moss",
		"scientific": "Tillandsia usneoides",
		"file": "/images/plants/tillandsia-usneoides.jpg",
		"artist": "Gh5046 at English Wikipedia",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Spanish_moss_at_the_Mcbryde_Garden_in_hawaii.jpg"
	},
	{
		"common": "Jade vine",
		"scientific": "Strongylodon macrobotrys",
		"file": "/images/plants/strongylodon-macrobotrys.jpg",
		"artist": "andrewholle",
		"license": "CC0",
		"licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Strongylodon_macrobotrys,_Bagong_Silang,_Los_Ba%C3%B1os,_Laguna,_Philippines_1.jpg"
	},
	{
		"common": "Traveller's palm",
		"scientific": "Ravenala madagascariensis",
		"file": "/images/plants/ravenala-madagascariensis.jpg",
		"artist": "Dicklyon",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Ravenala,_travellers_palms,_on_Maui.jpg"
	},
	{
		"common": "Coco de mer",
		"scientific": "Lodoicea maldivica",
		"file": "/images/plants/lodoicea-maldivica.jpg",
		"artist": "WL~commonswiki",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Female_coco_de_mer_growth.jpg"
	},
	{
		"common": "Cannonball tree",
		"scientific": "Couroupita guianensis",
		"file": "/images/plants/couroupita-guianensis.jpg",
		"artist": "Fotokannan",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:CanonBall_tree_with_flowers_panmana_kollam.jpg"
	},
	{
		"common": "Dragon arum",
		"scientific": "Dracunculus vulgaris",
		"file": "/images/plants/dracunculus-vulgaris.jpg",
		"artist": "Jörg Hempel",
		"license": "CC BY-SA 3.0 de",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Dracunculus_vulgaris_LC0044.jpg"
	},
	{
		"common": "Amborella",
		"scientific": "Amborella trichopoda",
		"file": "/images/plants/amborella-trichopoda.jpg",
		"artist": "Scott Zona from Miami, Florida, USA",
		"license": "CC BY 2.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/2.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Amborella_trichopoda.jpg"
	},
	{
		"common": "Boquila",
		"scientific": "Boquila trifoliolata",
		"file": "/images/plants/boquila-trifoliolata.jpg",
		"artist": "Tony Rebelo",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Boquila_trifoliolata_(Parque_Nacional_Puyehue,_Chili)_1.jpg"
	},
	{
		"common": "Common bladderwort",
		"scientific": "Utricularia vulgaris",
		"file": "/images/plants/utricularia-vulgaris.jpg",
		"artist": "No machine-readable author provided. Veledan~commonswiki assumed (based on copyright claims).",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Uk_pond_bladderwort.jpg"
	},
	{
		"common": "Common butterwort",
		"scientific": "Pinguicula vulgaris",
		"file": "/images/plants/pinguicula-vulgaris.jpg",
		"artist": "Ivar Leidus",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Pinguicula_vulgaris_flower_(front_view)_-_Keila.jpg"
	},
	{
		"common": "Albany pitcher plant",
		"scientific": "Cephalotus follicularis",
		"file": "/images/plants/cephalotus-follicularis.jpg",
		"artist": "H. Zell",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Cephalotus_follicularis_0001.JPG"
	},
	{
		"common": "Cobra lily",
		"scientific": "Darlingtonia californica",
		"file": "/images/plants/darlingtonia-californica.jpg",
		"artist": "NoahElhardt (talk · contribs)",
		"license": "CC BY 2.5",
		"licenseUrl": "https://creativecommons.org/licenses/by/2.5",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Darlingtonia_californica_ne1.JPG"
	},
	{
		"common": "Sun pitcher",
		"scientific": "Heliamphora nutans",
		"file": "/images/plants/heliamphora-nutans.jpg",
		"artist": "Gérard Vigo",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Roraima_Heliamphora_nutans1.JPG"
	},
	{
		"common": "Attenborough's pitcher plant",
		"scientific": "Nepenthes attenboroughii",
		"file": "/images/plants/nepenthes-attenboroughii.jpg",
		"artist": "Dr. Alastair Robinson",
		"license": "CC BY 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Attlwr.jpg"
	},
	{
		"common": "Corkscrew plant",
		"scientific": "Genlisea violacea",
		"file": "/images/plants/genlisea-violacea.jpg",
		"artist": "No machine-readable author provided. Denis Barthel assumed (based on copyright claims).",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Genlisea_violacea.JPG"
	},
	{
		"common": "Waterwheel plant",
		"scientific": "Aldrovanda vesiculosa",
		"file": "/images/plants/aldrovanda-vesiculosa.jpg",
		"artist": "Unknown author",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:AldrovandaVesiculosaHabit.jpg"
	},
	{
		"common": "Rainbow plant",
		"scientific": "Byblis gigantea",
		"file": "/images/plants/byblis-gigantea.jpg",
		"artist": "Denis Barthel",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:ByblisGiganteaFlora.jpg"
	},
	{
		"common": "Gorgon's dewstick",
		"scientific": "Roridula gorgonias",
		"file": "/images/plants/roridula-gorgonias.jpg",
		"artist": "Tony Rebelo",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Roridula_gorgonias_Rebelo_2.jpg"
	},
	{
		"common": "Portuguese sundew",
		"scientific": "Drosophyllum lusitanicum",
		"file": "/images/plants/drosophyllum-lusitanicum.jpg",
		"artist": "Taken by Carsten Niehaus (user:Lumbar).",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Drosophyllum_lusitanicum_a.JPG"
	},
	{
		"common": "Yellow devil's claw",
		"scientific": "Ibicella lutea",
		"file": "/images/plants/ibicella-lutea.jpg",
		"artist": "Misolonax",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:IbicellaLutea1.jpg"
	},
	{
		"common": "Devil's claw",
		"scientific": "Proboscidea louisianica",
		"file": "/images/plants/proboscidea-louisianica.jpg",
		"artist": "John D. Byrd, Mississippi State University, Bugwood.org",
		"license": "CC BY 3.0 us",
		"licenseUrl": "https://creativecommons.org/licenses/by/3.0/us/deed.en",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Proboscidea_louisianica_5.jpg"
	},
	{
		"common": "Living stone",
		"scientific": "Lithops karasmontana",
		"file": "/images/plants/lithops-karasmontana.jpg",
		"artist": "Dornenwolf",
		"license": "CC BY 2.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/2.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Lithops_karasmontana_%22opalina%22.jpg"
	},
	{
		"common": "Conophytum",
		"scientific": "Conophytum bilobum",
		"file": "/images/plants/conophytum-bilobum.jpg",
		"artist": "yakovlev.alexey from Moscow, Russia",
		"license": "CC BY-SA 2.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Conophytum_bilobum_subsp._bilobum_(Aizoaceae)_(37539170111).jpg"
	},
	{
		"common": "Concrete leaf",
		"scientific": "Titanopsis calcarea",
		"file": "/images/plants/titanopsis-calcarea.jpg",
		"artist": "Magnus Björlin",
		"license": "CC BY 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Titanopsis_calcarea.jpg"
	},
	{
		"common": "Split rock",
		"scientific": "Pleiospilos nelii",
		"file": "/images/plants/pleiospilos-nelii.jpg",
		"artist": "ZooFari",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Pleiospilos_nelii_flower.jpg"
	},
	{
		"common": "Fairy elephant’s feet",
		"scientific": "Frithia pulchra",
		"file": "/images/plants/frithia-pulchra.jpg",
		"artist": "Christer Johansson",
		"license": "CC BY-SA 2.5",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Frithia_pulchra10.jpg"
	},
	{
		"common": "Desert rose",
		"scientific": "Adenium obesum",
		"file": "/images/plants/adenium-obesum.jpg",
		"artist": "This Photo was taken by Timothy A. Gonsalves. Feel free to use my photos, but please mention me as the author. I would much appreciate if you send me an email tagooty@yahoo.com or write on my talk page, for my information. Please contact me before commercial use. Please do not upload an edited image here without consulting me. I would like to make corrections only at my own source to ensure that the changes improve the image and are preserved.Otherwise you may upload an edited image with a new name. Please use one of the templates derivative or extract.",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Adenium_Obesum_Flower_Side_Macro_Mar22_D72_23052-58_ZS_P.jpg"
	},
	{
		"common": "Drumstick tree",
		"scientific": "Moringa oleifera",
		"file": "/images/plants/moringa-oleifera.jpg",
		"artist": "Venkatx5",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:DrumstickFlower.jpg"
	},
	{
		"common": "Namibian grape",
		"scientific": "Cyphostemma juttae",
		"file": "/images/plants/cyphostemma-juttae.jpg",
		"artist": "JonTheSucculentDude",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Young_Cyphostemma_juttae.jpg"
	},
	{
		"common": "Boojum tree",
		"scientific": "Fouquieria columnaris",
		"file": "/images/plants/fouquieria-columnaris.jpg",
		"artist": "Tomas Castelazo",
		"license": "CC BY 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Cirio_columnaris,_boojum_tree.jpg"
	},
	{
		"common": "Saguaro",
		"scientific": "Carnegiea gigantea",
		"file": "/images/plants/carnegiea-gigantea.jpg",
		"artist": "WClarke",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Carnegiea_gigantea_in_Saguaro_National_Park_near_Tucson,_Arizona_during_November_(58).jpg"
	},
	{
		"common": "Fishhook barrel cactus",
		"scientific": "Ferocactus wislizeni",
		"file": "/images/plants/ferocactus-wislizeni.jpg",
		"artist": "Susan Lynn PetersonSue in az",
		"license": "CC BY 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Ferocactus_wislizeni_flower.jpg"
	},
	{
		"common": "Bishop's cap",
		"scientific": "Astrophytum myriostigma",
		"file": "/images/plants/astrophytum-myriostigma.png",
		"artist": "Lemaire, Charles Antoine",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Astrophytum_myriostigma_Lem.png"
	},
	{
		"common": "Living rock cactus",
		"scientific": "Ariocarpus fissuratus",
		"file": "/images/plants/ariocarpus-fissuratus.jpg",
		"artist": "C T Johansson",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Ariocarpus_fissuratus-IMG_4228.jpg"
	},
	{
		"common": "Blossfeldia",
		"scientific": "Blossfeldia liliputana",
		"file": "/images/plants/blossfeldia-liliputana.jpg",
		"artist": "Michael Wolf",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Blossfeldia_liliputana_20130512.jpg"
	},
	{
		"common": "Peyote",
		"scientific": "Lophophora williamsii",
		"file": "/images/plants/lophophora-williamsii.jpg",
		"artist": "Unknown author",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Peyote_Cactus.jpg"
	},
	{
		"common": "Barbados gooseberry",
		"scientific": "Pereskia aculeata",
		"file": "/images/plants/pereskia-aculeata.jpg",
		"artist": "Pereskia_aculeata4.jpg: Kauderwelsch derivative work: Peter coxhead (talk)",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Pereskia_aculeata4_cropped.jpg"
	},
	{
		"common": "Mistletoe cactus",
		"scientific": "Rhipsalis baccifera",
		"file": "/images/plants/rhipsalis-baccifera.jpg",
		"artist": "Frank Vincentz",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Rhipsalis_baccifera_01_ies.jpg"
	},
	{
		"common": "Queen of the night",
		"scientific": "Selenicereus grandiflorus",
		"file": "/images/plants/selenicereus-grandiflorus.jpg",
		"artist": "Johann Jakob Haid",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Johann_Jacob_Haid_Cereus.jpg"
	},
	{
		"common": "Dutchman's pipe cactus",
		"scientific": "Epiphyllum oxypetalum",
		"file": "/images/plants/epiphyllum-oxypetalum.jpg",
		"artist": "take by MAK, Wing Kuen. Photo taken in Hong Kong.",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Epiphyllum_oxypetalum_flower.JPG"
	},
	{
		"common": "Prickly pear",
		"scientific": "Opuntia ficus-indica",
		"file": "/images/plants/opuntia-ficus-indica.jpg",
		"artist": "YG01",
		"license": "CC BY 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Dikenli_%C4%B0ncir_(Opuntia_ficus-indica)_Gaziantep_Turkey.IMG_1104.jpg"
	},
	{
		"common": "Peruvian apple cactus",
		"scientific": "Cereus repandus",
		"file": "/images/plants/cereus-repandus.jpg",
		"artist": "Serge Melki from Indianapolis, USA",
		"license": "CC BY 2.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/2.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Cereus_repandus_in_Aruba_-_on_the_way_back_from_Altovista_chapel_(2896840490).jpg"
	},
	{
		"common": "Peruvian old man cactus",
		"scientific": "Espostoa lanata",
		"file": "/images/plants/espostoa-lanata.jpg",
		"artist": "Stan Shebs",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Espostoa_lanata_var_gracilis_2.jpg"
	},
	{
		"common": "Old man cactus",
		"scientific": "Cephalocereus senilis",
		"file": "/images/plants/cephalocereus-senilis.jpg",
		"artist": "Unknown author",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Cephalocereus_senilis.jpg"
	},
	{
		"common": "Mexican giant cardon",
		"scientific": "Pachycereus pringlei",
		"file": "/images/plants/pachycereus-pringlei.jpg",
		"artist": "Amante Darmanin from Malta",
		"license": "CC BY 2.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/2.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Pachycereus_pringlei_(5782057703).jpg"
	},
	{
		"common": "Golden barrel cactus",
		"scientific": "Echinocactus grusonii",
		"file": "/images/plants/echinocactus-grusonii.jpg",
		"artist": "André Karwath aka Aka",
		"license": "CC BY-SA 2.5",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Echinocactus_grusonii_(aka).jpg"
	},
	{
		"common": "Ladyfinger cactus",
		"scientific": "Mammillaria elongata",
		"file": "/images/plants/mammillaria-elongata.jpg",
		"artist": "Chhe (talk)",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:MammillariaElongata2.jpg"
	},
	{
		"common": "Moon cactus",
		"scientific": "Gymnocalycium mihanovichii",
		"file": "/images/plants/gymnocalycium-mihanovichii.jpg",
		"artist": "Petar43",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Gymnocalycium_mihanovichii_4.JPG"
	},
	{
		"common": "Christmas cactus",
		"scientific": "Schlumbergera truncata",
		"file": "/images/plants/schlumbergera-truncata.jpg",
		"artist": "Hooker, William Jackson, Sir Blackwood, William, publisher; Cadell, Thomas, publisher; Swan, Joseph, engraver",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Schlumbergera_truncata_(Exotic_Flora_Plate_20).jpg"
	},
	{
		"common": "Hoodia",
		"scientific": "Hoodia gordonii",
		"file": "/images/plants/hoodia-gordonii.jpg",
		"artist": "Winfried Bruenken (Amrum)",
		"license": "CC BY-SA 2.5",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Hoodia_gordonii_P1010383.JPG"
	},
	{
		"common": "Quiver tree",
		"scientific": "Aloe dichotoma",
		"file": "/images/plants/aloe-dichotoma.jpg",
		"artist": "Bjørn Christian Tørrissen",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:QuiverTree-Namibia-2015.JPG"
	},
	{
		"common": "Spiral aloe",
		"scientific": "Aloe polyphylla",
		"file": "/images/plants/aloe-polyphylla.jpg",
		"artist": "Stan Shebs",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Aloe_polyphylla_3.jpg"
	},
	{
		"common": "Queen Victoria agave",
		"scientific": "Agave victoriae-reginae",
		"file": "/images/plants/agave-victoriae-reginae.jpg",
		"artist": "Stan Shebs",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Agave_victoriae-reginae_lv_2.jpg"
	},
	{
		"common": "Joshua tree",
		"scientific": "Yucca brevifolia",
		"file": "/images/plants/yucca-brevifolia.jpg",
		"artist": "Bernard Gagnon",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Joshua_Tree_01.jpg"
	},
	{
		"common": "Ponytail palm",
		"scientific": "Beaucarnea recurvata",
		"file": "/images/plants/beaucarnea-recurvata.jpg",
		"artist": "juancruzado",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Beaucarnea_recurvata,_Ocampo,_Tamaulipas,_Mexico_1.jpg"
	},
	{
		"common": "Chestnut dioon",
		"scientific": "Dioon edule",
		"file": "/images/plants/dioon-edule.jpg",
		"artist": "C T Johansson",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Dioon_edule-IMG_9697.JPG"
	},
	{
		"common": "Sago palm",
		"scientific": "Cycas revoluta",
		"file": "/images/plants/cycas-revoluta.jpg",
		"artist": "Stan Shebs",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Cycas_inflorescence.jpg"
	},
	{
		"common": "Cardboard palm",
		"scientific": "Zamia furfuracea",
		"file": "/images/plants/zamia-furfuracea.jpg",
		"artist": "Unknown author",
		"license": "CC BY-SA 2.5",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Zamia_furfuracea03.jpg"
	},
	{
		"common": "Natal grass cycad",
		"scientific": "Stangeria eriopus",
		"file": "/images/plants/stangeria-eriopus.jpg",
		"artist": "Unknown author",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Stangeria_eriopus001.jpg"
	},
	{
		"common": "Zamia fern",
		"scientific": "Bowenia spectabilis",
		"file": "/images/plants/bowenia-spectabilis.jpg",
		"artist": "PeregrinusX",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Bowenia_Spectabilis_2_years.jpg"
	},
	{
		"common": "Moore’s cycad",
		"scientific": "Macrozamia moorei",
		"file": "/images/plants/macrozamia-moorei.jpg",
		"artist": "Unknown author",
		"license": "CC BY-SA 2.5",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Macrozamia_moorei01.jpg"
	},
	{
		"common": "Scaly zamia",
		"scientific": "Lepidozamia peroffskyana",
		"file": "/images/plants/lepidozamia-peroffskyana.jpg",
		"artist": "kaahuroa",
		"license": "CC BY 2.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/2.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Lepidozamia_peroffskyana_at_Kerikeri,_Bay_of_Islands,_New_Zealand.jpg"
	},
	{
		"common": "Palma corcho",
		"scientific": "Microcycas calocoma",
		"file": "/images/plants/microcycas-calocoma.jpg",
		"artist": "Unknown author",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Microcycas_calocoma01.jpg"
	},
	{
		"common": "Field horsetail",
		"scientific": "Equisetum arvense",
		"file": "/images/plants/equisetum-arvense.jpg",
		"artist": "MPF",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Equisetum_arvense_foliage.jpg"
	},
	{
		"common": "Whisk fern",
		"scientific": "Psilotum nudum",
		"file": "/images/plants/psilotum-nudum.jpg",
		"artist": "Unknown author",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Psilotum.jpg"
	},
	{
		"common": "Stag's-horn clubmoss",
		"scientific": "Lycopodium clavatum",
		"file": "/images/plants/lycopodium-clavatum.jpg",
		"artist": "Bernd Haynold",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Lycopodium_clavatum_151207.jpg"
	},
	{
		"common": "Lake quillwort",
		"scientific": "Isoetes lacustris",
		"file": "/images/plants/isoetes-lacustris.jpg",
		"artist": "Unknown author",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Illustration_Isoetes_lacustris0.jpg"
	},
	{
		"common": "Four-leaf clover fern",
		"scientific": "Marsilea quadrifolia",
		"file": "/images/plants/marsilea-quadrifolia.jpg",
		"artist": "Hardyplants",
		"license": "CC0",
		"licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Marsilea_quadrifolia_plants.jpg"
	},
	{
		"common": "Giant salvinia",
		"scientific": "Salvinia molesta",
		"file": "/images/plants/salvinia-molesta.jpg",
		"artist": "No machine-readable author provided. Marshman~commonswiki assumed (based on copyright claims).",
		"license": "CC BY 2.5",
		"licenseUrl": "https://creativecommons.org/licenses/by/2.5",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Salvinia_molesta.jpg"
	},
	{
		"common": "Water fern",
		"scientific": "Azolla filiculoides",
		"file": "/images/plants/azolla-filiculoides.jpg",
		"artist": "Len Worthington",
		"license": "CC BY-SA 2.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Water_Fern_Azolla_filiculoides_(6165580451).jpg"
	},
	{
		"common": "Royal fern",
		"scientific": "Osmunda regalis",
		"file": "/images/plants/osmunda-regalis.jpg",
		"artist": "E Wusk",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Osmunda_regalis_Mimizan.jpg"
	},
	{
		"common": "Black tree fern",
		"scientific": "Cyathea medullaris",
		"file": "/images/plants/cyathea-medullaris.jpg",
		"artist": "wikimedia user gerald.w",
		"license": "CC BY 2.5",
		"licenseUrl": "https://creativecommons.org/licenses/by/2.5",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Cyathea_medullaris.JPG"
	},
	{
		"common": "King fern",
		"scientific": "Angiopteris evecta",
		"file": "/images/plants/angiopteris-evecta.jpg",
		"artist": "brewbooks from near Seattle, USA",
		"license": "CC BY-SA 2.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Flickr_-_brewbooks_-_Angiopteris_evecta_-_Mule%27s_foot_fern_(1).jpg"
	},
	{
		"common": "Adder's-tongue",
		"scientific": "Ophioglossum vulgatum",
		"file": "/images/plants/ophioglossum-vulgatum.jpg",
		"artist": "Orchi",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Ophioglossum_vulgatum_Saarland_01.jpg"
	},
	{
		"common": "Moonwort",
		"scientific": "Botrychium lunaria",
		"file": "/images/plants/botrychium-lunaria.jpg",
		"artist": "Abalg",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Botrychium_lunaria_(Vanoise).JPG"
	},
	{
		"common": "Staghorn fern",
		"scientific": "Platycerium bifurcatum",
		"file": "/images/plants/platycerium-bifurcatum.jpg",
		"artist": "Krzysztof Ziarnek, Kenraiz",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Platycerium_bifurcatum_kz01.jpg"
	},
	{
		"common": "Bird's-nest fern",
		"scientific": "Asplenium nidus",
		"file": "/images/plants/asplenium-nidus.jpg",
		"artist": "Obsidian Soul",
		"license": "CC0",
		"licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Asplenium_nidus_(Bukidnon,_Philippines)_02.jpg"
	},
	{
		"common": "Maidenhair fern",
		"scientific": "Adiantum capillus-veneris",
		"file": "/images/plants/adiantum-capillus-veneris.jpg",
		"artist": "Balles2601",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Adiantum_capillus-veneris_2601.jpg"
	},
	{
		"common": "Bracken",
		"scientific": "Pteridium aquilinum",
		"file": "/images/plants/pteridium-aquilinum.jpg",
		"artist": "Rasbak",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Adelaarsvaren_planten_Pteridium_aquilinum.jpg"
	},
	{
		"common": "Ostrich fern",
		"scientific": "Matteuccia struthiopteris",
		"file": "/images/plants/matteuccia-struthiopteris.jpg",
		"artist": "The Cosmonaut",
		"license": "CC BY-SA 2.5 ca",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5/ca/deed.en",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Matteuccia_struthiopteris_fiddleheads.jpg"
	},
	{
		"common": "Peat moss",
		"scientific": "Sphagnum palustre",
		"file": "/images/plants/sphagnum-palustre.jpg",
		"artist": "James Lindsey at Ecology of Commanster",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Sphagnum.palustre.-.lindsey.jpg"
	},
	{
		"common": "Common liverwort",
		"scientific": "Marchantia polymorpha",
		"file": "/images/plants/marchantia-polymorpha.jpg",
		"artist": "HermannSchachner",
		"license": "CC0",
		"licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Marchantia_polymorpha_(b,_145318-481413)_3497.JPG"
	},
	{
		"common": "Field hornwort",
		"scientific": "Anthoceros agrestis",
		"file": "/images/plants/anthoceros-agrestis.jpg",
		"artist": "BerndH",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Anthoceros_agrestis_060910a.jpg"
	},
	{
		"common": "Giant moss",
		"scientific": "Dawsonia superba",
		"file": "/images/plants/dawsonia-superba.jpg",
		"artist": "Lisa Bennett",
		"license": "CC BY 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Dawsonia_superba_286409422.jpg"
	},
	{
		"common": "Common haircap",
		"scientific": "Polytrichum commune",
		"file": "/images/plants/polytrichum-commune.jpg",
		"artist": "Kristian Peters -- Fabelfroh 14:35, 21 October 2007 (UTC)",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Polytrichum_commune.jpeg"
	},
	{
		"common": "Lantern moss",
		"scientific": "Andreaea rupestris",
		"file": "/images/plants/andreaea-rupestris.jpg",
		"artist": "HermannSchachner",
		"license": "CC0",
		"licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Andreaea_rupestris_(c,_113340-471133)_6045.JPG"
	},
	{
		"common": "Common stonewort",
		"scientific": "Chara vulgaris",
		"file": "/images/plants/chara-vulgaris.jpg",
		"artist": "Chris F. Carter",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Chara_vulgaris_2007.jpg"
	},
	{
		"common": "Eelgrass",
		"scientific": "Zostera marina",
		"file": "/images/plants/zostera-marina.jpg",
		"artist": "Daderot",
		"license": "CC0",
		"licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Zostera_marina_-_National_Museum_of_Nature_and_Science,_Tokyo_-_DSC07663.JPG"
	},
	{
		"common": "Neptune grass",
		"scientific": "Posidonia oceanica",
		"file": "/images/plants/posidonia-oceanica.jpg",
		"artist": "Frédéric Ducarme",
		"license": "CC BY-SA 4.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Posidonia_oceanica_(L).jpg"
	},
	{
		"common": "Watermeal",
		"scientific": "Wolffia globosa",
		"file": "/images/plants/wolffia-globosa.jpg",
		"artist": "Unknown author",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Duckweeds.jpg"
	},
	{
		"common": "Common duckweed",
		"scientific": "Lemna minor",
		"file": "/images/plants/lemna-minor.jpg",
		"artist": "Unknown author",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Eendekroos_dicht_bijeen.JPG"
	},
	{
		"common": "Thale cress",
		"scientific": "Arabidopsis thaliana",
		"file": "/images/plants/arabidopsis-thaliana.jpg",
		"artist": "Original uploader was Brona at en.wikipedia. User:Roepers at nl.wikipedia",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Arabidopsis_thaliana.jpg"
	},
	{
		"common": "Rice",
		"scientific": "Oryza sativa",
		"file": "/images/plants/oryza-sativa.jpg",
		"artist": "Augustus Binu",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Mature_Rice_(India)_by_Augustus_Binu.jpg"
	},
	{
		"common": "Maize",
		"scientific": "Zea mays",
		"file": "/images/plants/zea-mays.jpg",
		"artist": "Franz Eugen Köhler, Köhler's Medizinal-Pflanzen",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Zea_mays_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-283.jpg"
	},
	{
		"common": "Bread wheat",
		"scientific": "Triticum aestivum",
		"file": "/images/plants/triticum-aestivum.jpg",
		"artist": "INRA DIST from France",
		"license": "CC BY 2.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/2.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Bl%C3%A9_tendre_(GRAPELLI)_AO-5-cliche_Jean_Weber_(5)_(23975019962).jpg"
	},
	{
		"common": "Barley",
		"scientific": "Hordeum vulgare",
		"file": "/images/plants/hordeum-vulgare.jpg",
		"artist": "Cliff from Arlington, Virginia, USA",
		"license": "CC BY 2.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/2.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Barley_(Hordeum_vulgare)_-_United_States_National_Arboretum_-_24_May_2009.jpg"
	},
	{
		"common": "Tomato",
		"scientific": "Solanum lycopersicum",
		"file": "/images/plants/solanum-lycopersicum.jpg",
		"artist": "Softeis",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Tomato_je.jpg"
	},
	{
		"common": "Potato",
		"scientific": "Solanum tuberosum",
		"file": "/images/plants/solanum-tuberosum.jpg",
		"artist": "Scott Bauer, USDA ARS",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Patates.jpg"
	},
	{
		"common": "Habanero",
		"scientific": "Capsicum chinense",
		"file": "/images/plants/capsicum-chinense.jpg",
		"artist": "André Karwath aka Aka",
		"license": "CC BY-SA 2.5",
		"licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Habanero_chile_-_fruits_(aka).jpg"
	},
	{
		"common": "Cacao",
		"scientific": "Theobroma cacao",
		"file": "/images/plants/theobroma-cacao.jpg",
		"artist": "Luisovalles",
		"license": "CC BY 3.0",
		"licenseUrl": "https://creativecommons.org/licenses/by/3.0",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Matadecacao.jpg"
	},
	{
		"common": "Arabica coffee",
		"scientific": "Coffea arabica",
		"file": "/images/plants/coffea-arabica.jpg",
		"artist": "Marcelo Corrêa",
		"license": "CC BY-SA 3.0",
		"licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Coffee_Flowers.JPG"
	},
	{
		"common": "Tea plant",
		"scientific": "Camellia sinensis",
		"file": "/images/plants/camellia-sinensis.jpg",
		"artist": "AxelBoldt at en.wikipedia",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Csinensis.jpg"
	},
	{
		"common": "Vanilla orchid",
		"scientific": "Vanilla planifolia",
		"file": "/images/plants/vanilla-planifolia.jpg",
		"artist": "Franz Eugen Köhler, Köhler's Medizinal-Pflanzen",
		"license": "Public domain",
		"licenseUrl": "",
		"sourceUrl": "https://commons.wikimedia.org/wiki/File:Vanilla_planifolia_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-278.jpg"
	}
];
