// Candidate species for the result-card plants. Deliberately over-supplied:
// the fetcher keeps the first 128 that resolve to a freely-licensed lead
// image on Wikimedia Commons, so entries that 404, lack a photo, or carry an
// unusable license simply fall through.
//
// Selection bias is toward binomials that read well deadpan under a
// certificate — the taker is told they are a Welwitschia mirabilis and given
// no further explanation.
export const SPECIES = [
	['Amorphophallus titanum', 'Titan arum'],
	['Welwitschia mirabilis', 'Welwitschia'],
	['Dionaea muscipula', 'Venus flytrap'],
	['Rafflesia arnoldii', 'Corpse lily'],
	['Dracaena cinnabari', 'Socotra dragon tree'],
	['Adansonia digitata', 'Baobab'],
	['Victoria amazonica', 'Giant water lily'],
	['Nepenthes rajah', 'Rajah pitcher plant'],
	['Selaginella lepidophylla', 'Resurrection plant'],
	['Hydnora africana', 'Jackal food'],
	['Psychotria elata', "Hooker's lips"],
	['Ophrys apifera', 'Bee orchid'],
	['Mimosa pudica', 'Sensitive plant'],
	['Ginkgo biloba', 'Ginkgo'],
	['Sequoiadendron giganteum', 'Giant sequoia'],
	['Drosera capensis', 'Cape sundew'],
	['Puya raimondii', 'Queen of the Andes'],
	['Encephalartos woodii', "Wood's cycad"],
	['Aristolochia gigantea', "Brazilian Dutchman's pipe"],
	['Stapelia gigantea', 'Carrion flower'],
	['Euphorbia obesa', 'Baseball plant'],
	['Pachypodium namaquanum', 'Halfmens'],
	['Wollemia nobilis', 'Wollemi pine'],
	['Monotropa uniflora', 'Ghost pipe'],
	['Sarracenia purpurea', 'Purple pitcher plant'],
	['Nelumbo nucifera', 'Sacred lotus'],
	['Tillandsia usneoides', 'Spanish moss'],
	['Strongylodon macrobotrys', 'Jade vine'],
	['Ravenala madagascariensis', "Traveller's palm"],
	['Lodoicea maldivica', 'Coco de mer'],
	['Couroupita guianensis', 'Cannonball tree'],
	['Dracunculus vulgaris', 'Dragon arum'],
	['Amborella trichopoda', 'Amborella'],
	['Boquila trifoliolata', 'Boquila'],
	['Utricularia vulgaris', 'Common bladderwort'],
	['Pinguicula vulgaris', 'Common butterwort'],
	['Cephalotus follicularis', 'Albany pitcher plant'],
	['Darlingtonia californica', 'Cobra lily'],
	['Heliamphora nutans', 'Sun pitcher'],
	['Nepenthes attenboroughii', "Attenborough's pitcher plant"],
	['Genlisea violacea', 'Corkscrew plant'],
	['Aldrovanda vesiculosa', 'Waterwheel plant'],
	['Byblis gigantea', 'Rainbow plant'],
	['Roridula gorgonias', "Gorgon's dewstick"],
	['Drosophyllum lusitanicum', 'Portuguese sundew'],
	['Ibicella lutea', "Yellow devil's claw"],
	['Proboscidea louisianica', "Devil's claw"],
	['Lithops karasmontana', 'Living stone'],
	['Fenestraria rhopalophylla', 'Baby toes'],
	['Conophytum bilobum', 'Conophytum'],
	['Titanopsis calcarea', 'Concrete leaf'],
	['Pleiospilos nelii', 'Split rock'],
	['Frithia pulchra', 'Fairy elephant’s feet'],
	['Adenium obesum', 'Desert rose'],
	['Moringa oleifera', 'Drumstick tree'],
	['Cyphostemma juttae', 'Namibian grape'],
	['Fouquieria columnaris', 'Boojum tree'],
	['Carnegiea gigantea', 'Saguaro'],
	['Ferocactus wislizeni', 'Fishhook barrel cactus'],
	['Astrophytum myriostigma', "Bishop's cap"],
	['Ariocarpus fissuratus', 'Living rock cactus'],
	['Blossfeldia liliputana', 'Blossfeldia'],
	['Lophophora williamsii', 'Peyote'],
	['Pereskia aculeata', 'Barbados gooseberry'],
	['Rhipsalis baccifera', 'Mistletoe cactus'],
	['Selenicereus grandiflorus', 'Queen of the night'],
	['Epiphyllum oxypetalum', "Dutchman's pipe cactus"],
	['Opuntia ficus-indica', 'Prickly pear'],
	['Cereus repandus', 'Peruvian apple cactus'],
	['Espostoa lanata', 'Peruvian old man cactus'],
	['Cephalocereus senilis', 'Old man cactus'],
	['Pachycereus pringlei', 'Mexican giant cardon'],
	['Echinocactus grusonii', 'Golden barrel cactus'],
	['Mammillaria elongata', 'Ladyfinger cactus'],
	['Gymnocalycium mihanovichii', 'Moon cactus'],
	['Schlumbergera truncata', 'Christmas cactus'],
	['Hoodia gordonii', 'Hoodia'],
	['Aloe dichotoma', 'Quiver tree'],
	['Aloe polyphylla', 'Spiral aloe'],
	['Agave victoriae-reginae', 'Queen Victoria agave'],
	['Yucca brevifolia', 'Joshua tree'],
	['Beaucarnea recurvata', 'Ponytail palm'],
	['Dioon edule', 'Chestnut dioon'],
	['Cycas revoluta', 'Sago palm'],
	['Zamia furfuracea', 'Cardboard palm'],
	['Stangeria eriopus', 'Natal grass cycad'],
	['Bowenia spectabilis', 'Zamia fern'],
	['Macrozamia moorei', 'Moore’s cycad'],
	['Lepidozamia peroffskyana', 'Scaly zamia'],
	['Microcycas calocoma', 'Palma corcho'],
	['Equisetum arvense', 'Field horsetail'],
	['Psilotum nudum', 'Whisk fern'],
	['Lycopodium clavatum', "Stag's-horn clubmoss"],
	['Isoetes lacustris', 'Lake quillwort'],
	['Marsilea quadrifolia', 'Four-leaf clover fern'],
	['Salvinia molesta', 'Giant salvinia'],
	['Azolla filiculoides', 'Water fern'],
	['Osmunda regalis', 'Royal fern'],
	['Dicksonia antarctica', 'Soft tree fern'],
	['Cyathea medullaris', 'Black tree fern'],
	['Angiopteris evecta', 'King fern'],
	['Ophioglossum vulgatum', "Adder's-tongue"],
	['Botrychium lunaria', 'Moonwort'],
	['Platycerium bifurcatum', 'Staghorn fern'],
	['Asplenium nidus', "Bird's-nest fern"],
	['Adiantum capillus-veneris', 'Maidenhair fern'],
	['Pteridium aquilinum', 'Bracken'],
	['Matteuccia struthiopteris', 'Ostrich fern'],
	['Sphagnum palustre', 'Peat moss'],
	['Marchantia polymorpha', 'Common liverwort'],
	['Anthoceros agrestis', 'Field hornwort'],
	['Buxbaumia aphylla', 'Bug moss'],
	['Dawsonia superba', 'Giant moss'],
	['Polytrichum commune', 'Common haircap'],
	['Andreaea rupestris', 'Lantern moss'],
	['Chara vulgaris', 'Common stonewort'],
	['Zostera marina', 'Eelgrass'],
	['Posidonia oceanica', 'Neptune grass'],
	['Wolffia globosa', 'Watermeal'],
	['Lemna minor', 'Common duckweed'],
	['Arabidopsis thaliana', 'Thale cress'],
	['Oryza sativa', 'Rice'],
	['Zea mays', 'Maize'],
	['Triticum aestivum', 'Bread wheat'],
	['Hordeum vulgare', 'Barley'],
	['Solanum lycopersicum', 'Tomato'],
	['Solanum tuberosum', 'Potato'],
	['Capsicum chinense', 'Habanero'],
	['Theobroma cacao', 'Cacao'],
	['Coffea arabica', 'Arabica coffee'],
	['Camellia sinensis', 'Tea plant'],
	['Vanilla planifolia', 'Vanilla orchid'],
	['Piper nigrum', 'Black pepper'],
	['Myristica fragrans', 'Nutmeg'],
	['Syzygium aromaticum', 'Clove'],
	['Cinnamomum verum', 'Ceylon cinnamon'],
	['Crocus sativus', 'Saffron crocus'],
	['Ferula assa-foetida', 'Asafoetida'],
	['Nepenthes bicalcarata', 'Fanged pitcher plant'],
	['Dracula simia', 'Monkey orchid'],
	['Ophrys insectifera', 'Fly orchid'],
	['Orchis italica', 'Naked man orchid'],
	['Caleana major', 'Flying duck orchid'],
	['Habenaria radiata', 'White egret orchid'],
	['Impatiens psittacina', 'Parrot flower'],
	['Calceolaria uniflora', "Darwin's slipper"],
	['Passiflora incarnata', 'Maypop'],
	['Amorphophallus konjac', 'Konjac'],
	['Arum maculatum', 'Lords-and-ladies'],
	['Symplocarpus foetidus', 'Skunk cabbage'],
	['Lysichiton americanus', 'Western skunk cabbage'],
	['Sauromatum venosum', 'Voodoo lily'],
	['Helicodiceros muscivorus', 'Dead horse arum'],
	['Nymphaea caerulea', 'Blue lotus'],
	['Cornus canadensis', 'Bunchberry dogwood'],
	['Silene tomentosa', 'Gibraltar campion'],
	['Franklinia alatamaha', 'Franklin tree'],
	['Sophora toromiro', 'Toromiro'],
	['Abies bracteata', 'Bristlecone fir'],
	['Pinus longaeva', 'Great Basin bristlecone pine'],
	['Metasequoia glyptostroboides', 'Dawn redwood'],
	['Taxus baccata', 'English yew'],
	['Araucaria araucana', 'Monkey puzzle tree'],
	['Agathis australis', 'Kauri'],
	['Cupressus dupreziana', 'Saharan cypress'],
	['Juniperus communis', 'Common juniper']
];
